#!/bin/bash

set -e

is_force=false
is_del_current_br=false

while (( $# > 0 ))
do
    case "$1" in
        -f)
            is_force=true
            ;;
        -d)
            is_del_current_br=true
            ;;
        -s)
            git fetch --prune --all
            git branch --merged \
                | grep -v '^*' \
                | xargs git branch -d
            exit $?
            ;;
    esac
    shift
done

branch="$(
git branch --color -a \
    | grep -v '*' \
    | sed -E 's/^ +//' \
    | fzy \
    | perl -pe 's/\e\[?.*?[\@-~]//g'
)"

if [[ -z $branch ]]; then
    exit 0
fi

current_branch=`git symbolic-ref --short HEAD 2>/dev/null;`

is_already_branched() { git branch | grep -q "${branch#*/*/}" &>/dev/null; }

if [[ $branch =~ ^remotes ]]; then
    if is_already_branched; then
        # already exists
        if $is_force; then
            git switch -q master
            git branch -D "${branch#*/*/}"
            git switch -c "${branch#*/*/}" "${branch#*/}"
        else
            git switch "${branch#*/*/}"
        fi
    else
        git switch -c "${branch#*/*/}" "${branch#*/}"
    fi
else
    if is_already_branched; then
        git switch "$branch"
    else
        git switch -c "$branch"
    fi
fi

if $is_del_current_br; then
    if [ -n "$current_branch" ]; then
        git branch -D $current_branch
    fi
fi
